<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
           vc:minVersion="1.1">
  <xs:element name="cardlatex">
    <xs:complexType>
      <xs:sequence maxOccurs="unbounded">
        {% if not texelements %}
          <xs:element name="tex" type="__init__"/>
        {% else %}
          <xs:element name="tex">
          {% for texelement in texelements %}
            <xs:alternative test="@file = '{{ texelement.file }}'" type="{{ texelement.type }}" />
          {% endfor %}
          </xs:element>
        {% endif %}
      </xs:sequence>
      <!--   use low resolution images, respect 'test' attributes and ignore 'copies' attributes   -->
      <xs:attribute name="draft" type="xs:boolean" use="required"/>
      <!--   ignore 'test' attributes   -->
      <xs:attribute name="print" type="xs:boolean" default="false"/>
      <!--   grid all cards onto <paper size>   -->
      <xs:attribute name="paper">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="A3"/>
            <xs:enumeration value="A4"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:attributeGroup name="tex">
    <xs:attribute name="file" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value=".+\.tex"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="dpi" type="xs:string" default="150"/>
    <xs:attribute name="spacing" type="measurement" default="0"/>
    <xs:attribute name="width" type="measurement" default="2.5in"/>
    <xs:attribute name="height" type="measurement" default="3.5in"/>
    <xs:attribute name="bleed" type="measurement" default="0.125in"/>
    <xs:attribute name="test">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="(\d+((-\d+)|(\.{2,}\d+))?,*)+"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>

  <xs:attributeGroup name="card">
    <xs:attribute name="copies" default="1">
      <xs:simpleType>
        <xs:restriction base="xs:integer">
          <xs:minExclusive value="0"/>
          <xs:maxExclusive value="100"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>

  <xs:simpleType name="measurement">
    <xs:restriction base="xs:string">
      <xs:pattern value="\d+(\.\d+)?(cm|mm|in)?"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="__init__">
    <xs:sequence maxOccurs="unbounded">
      <xs:element name="card" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
          </xs:sequence>
          <xs:attributeGroup ref="card"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attributeGroup ref="tex"/>
  </xs:complexType>

  {% for texelement in texelements %}
  <xs:complexType name="{{ texelement.type }}">
    <xs:sequence maxOccurs="unbounded">
      <xs:element name="card" maxOccurs="unbounded">
        <xs:complexType>
          <xs:all minOccurs="0">
            {% for variable in texelement.variables %}
            <xs:element minOccurs="0" name="{{ variable }}" type="xs:string"/>
            {% endfor %}
          </xs:all>
          <xs:attributeGroup ref="card"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attributeGroup ref="tex"/>
  </xs:complexType>
  {% endfor %}
</xs:schema>
